Various VN2 tests (#208)

diff --git a/workloads/vn2/example-with-skr-sidecar.yaml b/workloads/vn2/example-with-skr-sidecar.yaml
--- a/workloads/vn2/example-with-skr-sidecar.yaml
+++ b/workloads/vn2/example-with-skr-sidecar.yaml
@@ -1,28 +1,51 @@
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: sample-pod
+  name: example-with-skr-sidecar
 spec:
-  replicas: 16
+  replicas: 1
   selector:
     matchLabels:
-      app: sample-pod
+      deployment: example-with-skr-sidecar
   template:
     metadata:
       labels:
-        app: sample-pod
+        deployment: example-with-skr-sidecar
       annotations:
         microsoft.containerinstance.virtualnode.ccepolicy: "cGFja2FnZSBwb2xpY3kKCmFwaV9zdm4gOj0gIjAuMTAuMCIKCm1vdW50X2RldmljZSA6PSB7ImFsbG93ZWQiOiB0cnVlfQptb3VudF9vdmVybGF5IDo9IHsiYWxsb3dlZCI6IHRydWV9CmNyZWF0ZV9jb250YWluZXIgOj0geyJhbGxvd2VkIjogdHJ1ZSwgImVudl9saXN0IjogbnVsbCwgImFsbG93X3N0ZGlvX2FjY2VzcyI6IHRydWV9CnVubW91bnRfZGV2aWNlIDo9IHsiYWxsb3dlZCI6IHRydWV9IAp1bm1vdW50X292ZXJsYXkgOj0geyJhbGxvd2VkIjogdHJ1ZX0KZXhlY19pbl9jb250YWluZXIgOj0geyJhbGxvd2VkIjogdHJ1ZSwgImVudl9saXN0IjogbnVsbH0KZXhlY19leHRlcm5hbCA6PSB7ImFsbG93ZWQiOiB0cnVlLCAiZW52X2xpc3QiOiBudWxsLCAiYWxsb3dfc3RkaW9fYWNjZXNzIjogdHJ1ZX0Kc2h1dGRvd25fY29udGFpbmVyIDo9IHsiYWxsb3dlZCI6IHRydWV9CnNpZ25hbF9jb250YWluZXJfcHJvY2VzcyA6PSB7ImFsbG93ZWQiOiB0cnVlfQpwbGFuOV9tb3VudCA6PSB7ImFsbG93ZWQiOiB0cnVlfQpwbGFuOV91bm1vdW50IDo9IHsiYWxsb3dlZCI6IHRydWV9CmdldF9wcm9wZXJ0aWVzIDo9IHsiYWxsb3dlZCI6IHRydWV9CmR1bXBfc3RhY2tzIDo9IHsiYWxsb3dlZCI6IHRydWV9CnJ1bnRpbWVfbG9nZ2luZyA6PSB7ImFsbG93ZWQiOiB0cnVlfQpsb2FkX2ZyYWdtZW50IDo9IHsiYWxsb3dlZCI6IHRydWV9CnNjcmF0Y2hfbW91bnQgOj0geyJhbGxvd2VkIjogdHJ1ZX0Kc2NyYXRjaF91bm1vdW50IDo9IHsiYWxsb3dlZCI6IHRydWV9Cg=="
     spec:
       containers:
-      - name: helloworld-container
-        image: mcr.microsoft.com/aci/aci-confidential-helloworld:v1
+      - name: primary
+        image: quay.io/curl/curl:8.11.0
         resources:
           requests:
             memory: "2G"
             cpu: "1"
-        ports:
-        - containerPort: 80
+        command:
+          - sh
+          - -c
+          - |
+            while :; do
+              echo
+              echo
+              echo
+              curl -sSLv --data '{"runtime_data": "aGkK"}' http://127.0.0.1:8080/attest/raw
+              status=$?
+              echo # Adds a new line since the above endpoint doesn't
+              if [ $status -ne 0 ]; then
+                echo "curl failed"
+                sleep 5
+              else
+                echo "curl succeeded"
+                sleep 60
+              fi
+            done
+      - name: skr
+        image: mcr.microsoft.com/aci/skr:2.9
+        resources:
+          requests:
+            memory: "0.5G"
+            cpu: "0.5"
       nodeSelector:
         virtualization: virtualnode2
       tolerations:
